### ISSUE TITLE
Add checkbox to planned exercises

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#11]
# Value Proposition

**As a** user
**I want to** mark the exercises I have done
**So that** I have an overview about my progress while the training

# Description
![Image](https://user-images.githubusercontent.com/107792731/184652923-810d9e40-ccde-46e3-91c0-b91b5eae2e34.png)

# Acceptance Criteria

- [ ] There is a checkbox button on every card on the planner page
- [ ] when the checkbox button is clicked, it is marked 

# Tasks

- [ ] create a branch
- [ ] create StyledComponent for Checkbox Button
- [ ] add the StyledComponent Checkbox Button to the cards that are on the planner page
- [ ] add function with Global State Handling so that the checkbox is marked when clicked
 
# Complexity

M

**Comment by therealchrismcfly** [comment]
That's a good point :) I added it to the acceptance criteria!
