### ISSUE TITLE
Add your progress in the cards

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#13]
# Value Proposition

**As a** user
**I want to** write down (and edit) the weight, sets and repetition for every exercise
**So that** I can plan my workout more detailed.

# Description

![Image](https://user-images.githubusercontent.com/107792731/185608193-269f672f-2bf6-48c1-a292-02723640363c.png)

# Acceptance Criteria

- [ ] There are three input fields on every card for sets, reps and weight.
- [ ] Every input field has a label.
- [ ] only one entry per input field is possible
- [ ] the input value is set below the input field
- [ ] it is possible to edit the written input value
- [ ] the input is saved when the card is moved from index to planner page

# Tasks

- [ ] create a new branch
- [ ] create a Component for CardFooter
- [ ] Create a Component for Input Fields
- [ ] Put the InputFields in the CardFooter Component
- [ ] Map the CardFooter Component in the CardList of index.js and planner page
- [ ] write a function in GlobalStateHandling to set the inputValue 
- [ ] write down command to restrict adding more than one input per inputField
- [ ] write function to edit written input

# Complexity

![Image](https://user-images.githubusercontent.com/107792731/185608168-21f35279-8dd1-41c7-ad90-08ba0f4ae74d.png)

 L

**Comment by RobertBReich** [comment]
Hi Chris,
looks good to me. 👍
I would only use the input field and wouldn't put the result beneath it in the next row. 
You can add the icon to that input field with a ::before or ::after css tag and put it inside content: " ✎ " for example.

cheers
R.

**Comment by therealchrismcfly** [comment]
thanks for looking at my User Story and the advice :-) That would be my final plan but I don't know how to do it yet, so I wrote the User Story like this :D
