### ISSUE TITLE
Edit progress

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#15]
# Value Proposition

**As a** user
**I want to** I want to edit the sets, reps and weight
**So that** so that I can adjust my training progress for every exercise

# Description

![Image](https://user-images.githubusercontent.com/107792731/186126810-7d241769-5c7e-48aa-b81d-8ef199efeae9.png)

![Image](https://user-images.githubusercontent.com/107792731/186128988-7cdecd16-9e52-4c60-83ba-99a2a40772ee.png)

# Acceptance Criteria

- [ ] there is an edit button next to sets, reps and weight.
- [ ] when the user clicks the edit button, the input field opens and the user can change the entry
- [ ] when the user clicks submit (the hook), the new entry is saved.

# Tasks

- [ ] create a new feature branch
- [ ] create a styled component for the edit button
- [ ] implement the edit button on the Card Footer for every three fields
- [ ] write a function: when the edit button is clicked, the input field opens
- [ ] create a styled component for the submit button.
- [ ] implement the submit button in every three input fields
- [ ] write a function: when the submit button is clicked, the new value is saved and the input field is closed again.

# Complexity

M

**Comment by niklashmbgr** [comment]
looks good 👍 
as discussed it would be easier for the beginning to just have one edit button which controls one input field and later add the other two input fields.
