### ISSUE TITLE
Bookmark your favorite exercises

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#16]
# Value Proposition

**As a** user
**I want to** bookmark exercise cards
**So that** so that I have an overview about my favorite ones.

# Description

![Image](https://user-images.githubusercontent.com/107792731/185940719-7dc9d387-af01-4d83-bc64-6206c8fe00be.png)

# Acceptance Criteria

- [ ] every exercise card on the index.js has a bookmark icon
- [ ] when the bookmark icon is clicked, it is filled and the exercise card moves to the bookmark page
- [ ] there is a bookmark page in the navbar

# Tasks

- [ ] create a new feature branch
- [ ] create a bookmark page
- [ ] create a new cardlist component for the bookmarked exercise cards
- [ ] create a styled component for the bookmark button
- [ ] implement the bookmark button on every exercise card on the index page
- [ ] write a function with Zustand: When the bookmark button is clicked, the bookmark button is filled
- [ ] write a function with Zustand: When the bookmark button is clicked, the exercise card is moved to the bookmark page
- [ ] add routing

# Complexity

M

**Comment by RobertBReich** [comment]
Hey Chris,
the only thing that confused me a little was AC, 2nd sentence. 

How does this "move cards" work? I would think you add an entry somewhere in the bookmarks data, but here it sounds like you remove the card from the current view?

Maybe instead of "card moves to the bookmark page" you use "add card or (card entry) to the bookmark page" or something.

The rest looks good. 👍
cheers
R.
