### ISSUE TITLE
Add exercises to specific days of a week

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#17]
# Value Proposition

**As a** user
**I want to** add an exercise to a specific day of a week
**So that** I can usefully structure my weekly fitness plan in advance

# Description

![Image](https://user-images.githubusercontent.com/107792731/186150728-6d00e3f1-be08-4a33-9b03-09163226e9e0.png)

# Acceptance Criteria

- [ ] When the calendar button on a card (index.js) is clicked, a calendar appears.
- [ ] the upcoming 7 days are marked
- [ ] when the user clicks on a specific date the exercise is added to the corresponding day on the planner page

# Tasks
- [ ] create a new branch
- [ ] create a component for the calendar
- [ ] import React-Calendar in the component
- [ ] write a function: when the calendar button is clicked, the calendar opens.
- [ ] create components for Mo - Su
- [ ] import the components on the planner.js
- [ ] change the addCard function in useStore so that the exercise card is added to the corresponding day on the planner page.

# Complexity

XL

**Comment by RobertBReich** [comment]
Hi Chris,

looks good. 👍
