### ISSUE TITLE
Show & hide description text

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#21]
# Value Proposition

**As a** user
**I want to** show and hide the description text of an exercise
**So that** to adjust the current view to my needs.

# Description
![Image](https://user-images.githubusercontent.com/107792731/186923990-4efdd387-3508-4e61-8e21-6b77680331aa.png)

# Acceptance Criteria

- [ ] there is a "show instructions" - button on every exercise card (on every page)
- [ ] when the show instructions button is clicked, the button text changes to "hide" and the description text of the exercise is shown and vice versa.

# Tasks

- [ ] create a new branch
- [ ] create a styled component for the button and implement it
- [ ] write a toggle function to show and hide the description text by button click
- [ ] write a toggle function to change the button text by click.

# Complexity

M
