### ISSUE TITLE
Add Searchbar

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#22]
# Value Proposition

**As a** user
**I want to** have a searchbar
**So that** I'm able to easily find the exercises I'm looking for.

# Description

![Image](https://user-images.githubusercontent.com/107792731/186928560-3af8c6c9-c71c-4d6f-b8fd-ff4069a26b5a.png)

# Acceptance Criteria

- [ ] there is a search bar at the top of the index.js page
- [ ] when text it typed into the searchbar, exercise cards with the corresponding name will appear.

# Tasks

- [ ] create a new branch
- [ ] create a styled component for the searchbar and implement it
- [ ] implement fuzzy search

# Complexity

L
