### ISSUE TITLE
Filter the exercises by muscle group

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#25]
# Value Proposition

**As a** user
**I want to** have filter buttons
**So that** I'm able to find exercises for specific muscle groups

# Description

![Image](https://user-images.githubusercontent.com/107792731/187044593-ff4ed6ef-e4af-40d9-9550-fa7df80720db.png)

# Acceptance Criteria

- [ ] there are several Filter Buttons at the top of the index.js page
- [ ] when one button is clicked, exercise cards for the corresponding muscle group will appear.

# Tasks

- [ ] create a new branch
- [ ] create styled components for the Filter Buttons and implement them on Cardlist of index.js
- [ ] add categories to the cards data
- [ ] write a function for every button to filter the corresponding exercise cards.

# Complexity

L

**Comment by PhilipZi** [comment]
lgtm
