### ISSUE TITLE
Datenstuktur refactoring

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#26]
# Value Proposition

**As a** developer
**I want to** have better structured data
**So that** I can integrate the upcoming features and have cleaner code

# Description
- 

# Acceptance Criteria
- [ ] I have different data sets for planner and index.js
- [ ] all existing features do work

# Tasks
- [ ] restructure the data in useStore
- [ ] rewrite functions that depend on this data

# Complexity

L
