### ISSUE TITLE
See progress history

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#28]
# Value Proposition

**As a** user
**I want to** have a page for my progress history
**So that** I have an overview about my progress

# Description

![Image](https://user-images.githubusercontent.com/107792731/187627622-4424a54b-8513-423b-9dd1-22e5157af845.png)

# Acceptance Criteria

- [ ] there is a page in the navbar for the progress history
- [ ] There is a card for every exercise with its name
- [ ] there is a button below ever exercise to show and hide the progress history
- [ ] every time new values for the progress are added for an exercise, they appear on the progress history

# Tasks

- [ ] create a new branch
- [ ] create a styled component for the exercise card name
- [ ] create styled component for the history card
- [ ] integrate the data from the inputs of the planner page to the history card
- [ ] create a styled cardlist for the progress page
- [ ] add and map the exercise card name and history card on the cardlist
- [ ] create a progress page
- [ ] add progress page to routing
- [ ] add the cardlist to the progress page
- [ ] create a styled component for the show and hide button
- [ ] add a function to the cardlist, that the history card is shown and hidden by click on the button

# Complexity

XL
