### ISSUE TITLE
Add styling & upgrade UX

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#30]
# Value Proposition

**As a** user
**I want to** have a good looking interface and great usability
**So that** I'm having a good time using the app 

# Tasks 

- [ ] add Global Styles
- [ ] add colors
- [ ] add Google Fonts
- [ ] add icons instead of buttons
- [ ] add Feedback for the User (hover, on click)
- [ ] add final content (images & instructions)
- [ ] add formatting

# Complexity

XL
