### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#36]
# Value Proposition

**As a** developer
**I want to** refactor my code
**So that** it is clearer and better to read and understand

# Acceptance Criteria

- [ ] consistency in folder structure, naming
- [ ] no bugs / console errors
- [ ] clearer code

# Tasks
- [ ] restructure folder / file structure
- [ ] check for bugs / console errors
- [ ] check naming 
- [ ] css - redundant styles
- [ ] check if components can be reused

# Complexity

L
