### ISSUE TITLE
Add Cards to a List

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#4]
# Value Proposition

**As a** user
**I want to** add an exercise card to a list
**So that** I have a list of the exercises I want to do

# Description

![Image](https://user-images.githubusercontent.com/107792731/184366204-60e0ce37-a46f-4de7-b825-6cf7a4504de1.png)

![Image](https://user-images.githubusercontent.com/107792731/184366233-da51473f-7077-427f-a8c5-719cbd407810.png)

# Acceptance Criteria

- [ ] When the calendar button is clicked
- [ ] the card is moved to the planner page 
- [ ] the card also stays at the index page

# Tasks

- [ ] create a branch
- [ ] create a planner page
- [ ] create useStore 
- [ ] kann ich erst genau sagen, wenn ich daran arbeite

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Chris,

Great job 💪🏼 

I was just wondering how the user can switch between the main page and the planner page 🤔 this information should be visible in the scribble and mentioned in the acceptance criteria.

As well, I would suggest to erase the following:

>  Rest kann ich erst genau sagen, wenn ich daran arbeite

The goal is to write a complete user story with all tasks which need to be done. So that once you are implementing the feature of your user story, you only need to tick off the items on your task list. Plan first and then code 🙂 
So, I suggest to think carefully about, what you need and how you are going to implement it. Of course, this is a learning process. If you notice that you haven't mention all the tasks in your user story while coding, you can adjust the user story later on.

**Comment by RobertBReich** [comment]
Hey Chris,

looks great! Only thing i didn't fully understand is this "card also stays on the index" thing. 
I wouldn't say this is an acceptance criteria. You can make it a task, but i thought this is sort of a bookmark when you move an exercise to the planner? 🤔

other than that: 👍

cheers
R.

**Comment by RobertBReich** [comment]
👍

**Comment by ahohnsen** [comment]
Nice update 👍🏼 

> When the calendar button is clicked
the card is moved to the planner page

I would write this in one line: When the calendar button is clicked the card is moved to the planner page
