### ISSUE TITLE
Write Tests for functions

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#41]
# Value Proposition

**As a** developer
**I want to** write tests for components
**So that** I make sure everything works smoothly

# Acceptance Criteria

- [ ] working tests for at least three components

# Tasks

- [ ] Create new branch
- [ ] Create tests
- [ ] npm run test

# Complexity

L
