### ISSUE TITLE
Add information to the cards

### ISSUE THREAD

**Issue by therealchrismcfly** [therealchrismcfly/capstone-project#6]
# Value Proposition

**As a** user 
**I want to** see more information on the cards
**So that** I can see how to perform the exercises

# Description

![Image](https://user-images.githubusercontent.com/107792731/184368752-0dee1537-acce-4b31-bc98-ea6bf40be8a5.png)

# Acceptance Criteria

- [ ] the shown cards have an image 
- [ ] the shown cards have an instruction text

# Tasks

(for developers team)

- [ ] create branch
- [ ] add images to the database file
- [ ] add instruction text to the database file
- [ ] create a Styled Component for the image
- [ ] create a Styled Component for the instruction text
- [ ] add the image and text component to the Cardlist Component
- [ ] map the data to render it on the page

# Complexity

S

**Comment by ahohnsen** [comment]
Nice 💪🏼 

I would just suggest to always display the whole screen/app in your scribble instead of only part of it.
